# Generated by Django 2.2.2 on 2019-07-08 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190708_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='job_category',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 15, 56, 41, 373315)),
        ),
    ]
