# Generated by Django 2.2.2 on 2019-07-08 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190708_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 16, 4, 16, 541099)),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_category',
            field=models.IntegerField(choices=[(1, 'IT/Telecomunication'), (2, 'Engineering'), (3, 'Medical')]),
        ),
    ]
