# Generated by Django 2.2.2 on 2019-07-08 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190708_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traininginfo',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 21, 49, 17, 412473)),
        ),
    ]
