# Generated by Django 2.2.2 on 2019-07-08 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190708_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='job_category',
            new_name='jobcategory',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 22, 15, 13, 280239)),
        ),
    ]
