# Generated by Django 2.2.2 on 2019-07-09 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190708_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 19, 22, 45, 55168)),
        ),
        migrations.CreateModel(
            name='VacancyApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applieddate', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Selected'), (3, 'Rejected')], default=1)),
                ('jseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JobSeekerProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vacancy')),
            ],
        ),
    ]
