# Generated by Django 2.2.2 on 2019-07-11 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190709_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='category',
            field=models.IntegerField(choices=[(1, 'IT/Telecomunication'), (2, 'Engineering'), (3, 'Medical')], null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 7, 26, 11, 23, 59, 803358)),
        ),
    ]
