# Generated by Django 2.2.2 on 2019-07-11 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190711_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='category',
            new_name='interested_category',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 7, 26, 11, 24, 43, 529740)),
        ),
    ]
